// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO8k0SgT2Kn2aZHwDPiWmbzB8c91Rxo_c',
    appId: '1:481645468669:web:8714a55070631d399bd794',
    messagingSenderId: '481645468669',
    projectId: 'my-wcab',
    authDomain: 'my-wcab.firebaseapp.com',
    storageBucket: 'my-wcab.firebasestorage.app',
    measurementId: 'G-8GVVWCWRX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoB2aygpKIxVtlQM5Q-DYtwJoEZcH6gtQ',
    appId: '1:481645468669:android:727ae93e9964461e9bd794',
    messagingSenderId: '481645468669',
    projectId: 'my-wcab',
    storageBucket: 'my-wcab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf_qKdnljM0jM0BHP7jPmA2YgomUpznYA',
    appId: '1:481645468669:ios:63c9c8b4c5a36ba59bd794',
    messagingSenderId: '481645468669',
    projectId: 'my-wcab',
    storageBucket: 'my-wcab.firebasestorage.app',
    iosBundleId: 'com.example.myWorkoutCab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf_qKdnljM0jM0BHP7jPmA2YgomUpznYA',
    appId: '1:481645468669:ios:63c9c8b4c5a36ba59bd794',
    messagingSenderId: '481645468669',
    projectId: 'my-wcab',
    storageBucket: 'my-wcab.firebasestorage.app',
    iosBundleId: 'com.example.myWorkoutCab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO8k0SgT2Kn2aZHwDPiWmbzB8c91Rxo_c',
    appId: '1:481645468669:web:cca6dceab85d5da89bd794',
    messagingSenderId: '481645468669',
    projectId: 'my-wcab',
    authDomain: 'my-wcab.firebaseapp.com',
    storageBucket: 'my-wcab.firebasestorage.app',
    measurementId: 'G-G6YF4VBBLP',
  );
}
